# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20170613_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='startpassing_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
