# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_applicant_startpassing_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='startpassing_date',
        ),
    ]
