# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_remove_applicant_startpassing_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='startpassing_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
