# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_applicant_startpassing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='test_status',
            field=models.CharField(max_length=50),
        ),
    ]
