# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_applicant_qquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='submit_if_leave',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='test',
            name='timetest',
            field=models.IntegerField(default=2),
        ),
    ]
