# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_auto_20170621_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='passing_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='startpassing_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
