# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0014_user_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
