# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 14:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0016_auto_20170727_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='q_count',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='test',
            name='timetest',
            field=models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
