# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0017_auto_20170727_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tquestion',
            name='question',
            field=models.TextField(null=True),
        ),
    ]
