# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0018_auto_20170727_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tquestion',
            name='choicer1',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='tquestion',
            name='choicer2',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='tquestion',
            name='choicer3',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='tquestion',
            name='choicer4',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='tquestion',
            name='choicer5',
            field=models.BooleanField(),
        ),
    ]
