# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-14 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0020_user_activatecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='test_id',
            field=models.IntegerField(default=0),
        ),
    ]
